### PR TITLE
fix for #312 added checksum annotation to console deployment

### PR DESCRIPTION
**Pull request by acristu**
Added the config checksum annotation ... it works for my use cases, changing the brokers and schema registry url(s) trigger pod restart.

### CODE REVIEW

**Comment by acristu** [comment]
done

**Review by joejulian — APPROVED** [review]
lgtm. Thanks!

**Comment by joejulian** [comment]
Can you rebase this, please, so the tests will pass? I would do it for you but that checkbox wasn't checked.

**Comment by joejulian** [comment]
Well rats... It worked locally. Thanks!

**Pull request merged**
