### PR TITLE
Re-enable connectors in the e2e tests

### PR DESCRIPTION
**Pull request by RafalKorepta**
Fixes https://github.com/redpanda-data/helm-charts/issues/673

### CODE REVIEW

**Comment by joejulian** [comment]
Do we want to have it enabled for all 20 test runs, or would it be sufficient to just add it to 02, 03, 04, and 05?

**Comment by RafalKorepta** [comment]
> Do we want to have it enabled for all 20 test runs, or would it be sufficient to just add it to 02, 03, 04, and 05?

I would say 01, 07, 10, 11, 21, 22, 23, 99 should be added to. From that point out of 20 test cases we should exclude 8 test cases. 

Would you set the `connectors.enabled=true` inside the ci yaml files?

Maybe it would be better to include connectors by default and then exclude connectors from some test cases? 

P.S. The execution time is not that different :)

Without connectors: 54m 29s https://github.com/redpanda-data/helm-charts/actions/runs/6224097361

With connectors enabled: 1h 9m 29s https://github.com/redpanda-data/helm-charts/actions/runs/6225520431?pr=732

**Comment by alejandroEsc** [comment]
> Would you like to set the `connectors.enabled=true` inside the ci yaml files?

I do not mind this approach, but i think i would also prefer to have it explicitly on in a particular CI. Approving anyway, but thats my 2 cents.

**Review by joejulian — APPROVED** [review]

**Comment by RafalKorepta** [comment]
And problem manifested again 
```
TEST SUITE:     redpanda-toij1e433z-connectors-mm2-test-499
Last Started:   Tue Sep 19 20:51:12 2023
Last Completed: Tue Sep 19 20:51:26 2023
Phase:          Failed
```
https://github.com/redpanda-data/helm-charts/actions/runs/6240508804/job/16940776008#step:18:51171

**Comment by RafalKorepta** [comment]
latest problem
```
2023-09-19T23:44:16.0280646Z 4m54s       Warning   BackOff                 pod/redpanda-w4y9m9v3w6-0                             spec.initContainers{tuning}   kubelet, chart-testing-worker                                                                        Back-off restarting failed container tuning in pod redpanda-w4y9m9v3w6-0_redpanda-w4y9m9v3w6(1e6ec706-97a6-42c2-a511-fb14c15f291e)                           14m          48      redpanda-w4y9m9v3w6-0.178670a6774b25f7
2023-09-19T23:44:16.0282131Z 4m50s       Warning   BackOff                 pod/redpanda-w4y9m9v3w6-console-69bd5dff85-4fn78      spec.containers{console}      kubelet, chart-testing-worker2                                                                       Back-off restarting failed container console in pod redpanda-w4y9m9v3w6-console-69bd5dff85-4fn78_redpanda-w4y9m9v3w6(efb55ffc-bce6-4412-a4f0-86db2064933f)   12m          35      redpanda-w4y9m9v3w6-console-69bd5dff85-4fn78.178670c631f9773a
```

https://github.com/redpanda-data/helm-charts/actions/runs/6241967849/job/16945085643?pr=732#step:18:94

**Pull request merged**
