### PR TITLE
migrate KMinion chart

### PR DESCRIPTION
**Pull request by weeco**
This PR is the first step towards migrating the KMinion Helm chart from https://github.com/redpanda-data/kminion/tree/master/charts to this repository and team. No changes were made to the chart itself.

- Add Apache 2.0 headers
- Fix helm linters
- Regenerate README using helm-docs
- Align Chart.yaml definition to [artifactory hub](https://artifacthub.io/)
- Clean Github workflows to correctly run operator, redpanda and kminion
- Fix operator CI tests

cc @simon0191

### CODE REVIEW

**Review by RafalKorepta — APPROVED** [review]
I don't see problem, but could you move the comment that was rised by `Github Action/lint`.

**Comment by RafalKorepta** [comment]
Do you have any idea how CI test could look like for `KMinion`?

**Comment by weeco** [comment]
```
  Error: 52:14 [comments] too few spaces before comment
  Error: 53:19 [comments] too few spaces before comment
  Error: 54:18 [comments] too few spaces before comment
```

I see this error, but I have no clue what is wrong with this part or how it should look like instead. This affects this config block from the values.yaml.
```yaml
securityContext:
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
```

**Review by RafalKorepta — APPROVED** [review]

**Review by alejandroEsc — APPROVED** [review]
LGTM, One ask for the future is to split chart changes to different PRs or at least to different commits. This will allow us to revert if necessary quickly and cleanly.

**Comment by RafalKorepta** [comment]
> One ask for the future is to split chart changes to different PRs or at least to different commits. This will allow us to revert if necessary quickly and cleanly.

Which change/commit exactly as I can exclude CI changes to broken operator tests. Rest are necessary to add kminion chart to Redpanda family.

**Pull request merged**
