### PR TITLE
Improve connector docs

### PR DESCRIPTION
**Pull request by JakeSCahill**

### CODE REVIEW

**Review by RafalKorepta — APPROVED** [review]
LGTM, I would like to have additional approve from @bochenekmartin or @tomasz-sadura

**Review by tomasz-sadura — APPROVED** [review]
LGTM. Thanks!

**Review by bochenekmartin — APPROVED** [review]

**Comment by JakeSCahill** [comment]
@RafalKorepta is this one OK to merge? Not sure why the summary doesn't get generated.

**Comment by RafalKorepta** [comment]
https://github.com/redpanda-data/helm-charts/pull/820/commits/5c2b5b3e25f45fa18d8d84dd5903544a3de897ed

The above commit should unblock this PR.

**Comment by RafalKorepta** [comment]
KMinion lint is false positive. The Github workflow has changed (which trigger whole pipeline), but the underlaying chart didn't.

**Pull request merged**
