### PR TITLE
Handle extraObjects like secrets

### PR DESCRIPTION
**Pull request by RogerBonati**
Provide extraObjects template to handle secrets

### CODE REVIEW

**Comment by TheMeier** [comment]
Having such a mechanism is quite common in the helm world nowadays. Especially since it avoids creating custom charts around subcharts. Maybe you could re-consider

**Comment by chrisseto** [comment]
If you have any references to other charts that do this, I'll take a look and re-evaluate the decision. However, given that there are myriad ways for end users to deploy a set of manifests without modifications to an upstream chart, I don't see a particularly compelling for us to maintain such a feature.

**Comment by TheMeier** [comment]
@chrisseto 

Sure here is a few examples:

- [Grafana](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/extra-manifests.yaml)
- [Prometheus](https://github.com/prometheus-community/helm-charts/blob/5f64862e5d434ad33d358d4dae3b3256d7281e5c/charts/prometheus/templates/extra-manifests.yaml) (Many more of the prometheus-community charts have this)
- [Cert-Manager](https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/extras-objects.yaml)
- [Traefik](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/extra-objects.yaml)
- [Kubernetes-Autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/extra-manifests.yaml)
- [All of bitnami charts via their template for all charts](https://github.com/bitnami/charts/blob/main/template/CHART_NAME/templates/extra-list.yaml)

There is also an issue for helm to make this a helm-feature: https://github.com/helm/helm/issues/12653

**Comment by TheMeier** [comment]
@RafalKorepta @chrisseto any chance this is re-considered?

**Pull request closed without merging**
