### PR TITLE
Decrease cloud_storage_cache_size default value

### LINKED ISSUE #416: Dynamic tiered storage cache sizing
### What happened?

`cloud_storage_cache_size` is set to the same default size of the persistent disks. This means cache can possibly fill up the entire disk.

### What did you expect to happen?

This value should be calculated as a % of available local disk space, taking guidance from our new cloud tiers (including high throughput tiers). The cache should optionally also be created as its own persistent volume to isolate this storage from others.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
# paste output here
```

</details>

### Anything else we need to know?

_No response_

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### PR DESCRIPTION
**Pull request by vuldin**
Closes #416 

This value at it's current default of 20Gi is set to the same size as the default value for a persistent volume's size. This means that if consumers start consuming data from offset 0 and there is enough cloud storage data (over 20Gi), then the disk would be entirely consumed by cloud storage alone and crash the broker.

This PR sets the cloud storage cache storage value to a better default of 5Gi.

### CODE REVIEW

**Comment by joejulian** [comment]
There was a discussion that suggested that this should also be accompanied by a change to tiered storage such that this value is computed rather than just set. Did we want to do that here, or should it be a separate PR?

**Comment by vuldin** [comment]
> suggested that this should also be accompanied by a change to tiered storage such that this value is computed rather than just set. Did we want to do that here
I think it makes sense to include that change here. Another suggestion was to make the separate cloud storage PV enabled by default. Would we also want to include that related change here?

**Comment by joejulian** [comment]
> > suggested that this should also be accompanied by a change to tiered storage such that this value is computed rather than just set. Did we want to do that here

>  I think it makes sense to include that change here. Another suggestion was to make the separate cloud storage PV enabled by default. Would we also want to include that related change here?

Seems like a good idea to me.

**Comment by joejulian** [comment]
We're just going to accept this as-is and add an issue for the more sophisticated improvement: https://github.com/redpanda-data/helm-charts/issues/530

**Review by joejulian — APPROVED** [review]

**Pull request merged**
