### PR TITLE
#263 - workaround for k8s node taint and rack label having the same k…

### LINKED ISSUE #263: Improve rack awareness label discovery
Hello,

in our environment we are using taints on nodes with the same name as rack label. This is breaking this piece of code: https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/statefulset.yaml#L140
`RACK=$(curl --silent --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt --fail -H 'Authorization: Bearer '$(cat /run/secrets/kubernetes.io/serviceaccount/token) "https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}/api/v1/nodes/${KUBERNETES_NODE_NAME}?pretty=true" | grep {{ .Values.rackAwareness.nodeAnnotation | quote | squote }} | grep -v '\"key\":' | sed 's/.*": "\([^"]\+\).*/\1/')`

As a workaround we have added additional grep:
`.... | grep {{ .Values.rackAwareness.nodeAnnotation | quote | squote }} | grep -v '\"key\":' | sed 's/.*": "\([^"]\+\).*/\1/'`

It would be better to do it using for example jq but it would need to be added to the image.

### PR DESCRIPTION
**Pull request by burandobata**
Workaround for k8s node taint and rack label having the same key name.
Fixes #263

### CODE REVIEW

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
@burandobata If you could sign the CLA and rebase, we could get this merged.

**Comment by joejulian** [comment]
Sorry, didn't see the comment in the issue about the CLA already being signed. I'll get this merged.

**Comment by ivotron** [comment]
hi @burandobata , the problem is that the commit has a different email to the one you use for github. this needs to be reconciled so that the CLA check passes

**Comment by joejulian** [comment]
rebased

**Comment by RafalKorepta** [comment]
rebased

**Review by RafalKorepta — APPROVED** [review]

**Pull request merged**
