### PR TITLE
Add new topic custom resource RBAC rules

### PR DESCRIPTION
**Pull request by RafalKorepta**

### CODE REVIEW

**Review by joejulian — APPROVED** [review]

**Comment by joejulian** [comment]
Weird... why did the linter pass without a chart version bump?

**Comment by alejandroEsc** [comment]
good questions, let's not merge until we bump the version.

**Comment by RafalKorepta** [comment]
> Weird... why did the linter pass without a chart version bump?

https://github.com/redpanda-data/helm-charts/actions/runs/6123500972/job/16621530099?pr=708#step:6:12

```
Run changed=$(ct list-changed --target-branch main --config .github/ct-operator.yaml)
Version increment checking disabled.
```

I would say it's short coming of chart testing. 
```go
	if len(cfg.Charts) > 0 || cfg.ProcessAllCharts {
		fmt.Fprintln(os.Stderr, "Version increment checking disabled.")
		cfg.CheckVersionIncrement = false
	}
```
https://github.com/helm/chart-testing/blob/d910c7788b63f14f3d9383861a4f2cad920915ae/pkg/config/config.go#L164-L167

Which comes down to our charts list:

https://github.com/redpanda-data/helm-charts/blob/8d3918c20da8b66012f42be14219d3f5a3d843ae/.github/ct-operator.yaml#L21-L22

I would suggest to change the condition if we have only one charts to allow version increment check.
```go
	if len(cfg.Charts) > 1 || cfg.ProcessAllCharts {
		fmt.Fprintln(os.Stderr, "Version increment checking disabled.")
		cfg.CheckVersionIncrement = false
	}
```

**Comment by RafalKorepta** [comment]
FYI https://github.com/helm/chart-testing/pull/594

**Comment by RafalKorepta** [comment]
```
rpk topic create test -v
  09:44:36.848  DEBUG  opening connection to broker  {"addr": "cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local:9092", "broker": "seed_0"}
  09:44:36.861  WARN  unable to open connection to broker  {"addr": "cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local:9092", "broker": "seed_0", "err": "dial tcp: lookup cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local on 10.96.0.10:53: no such host"}
  09:44:36.861  DEBUG  opening connection to broker  {"addr": "cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local:9092", "broker": "seed_0"}
  09:44:36.873  WARN  unable to open connection to broker  {"addr": "cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local:9092", "broker": "seed_0", "err": "dial tcp: lookup cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local on 10.96.0.10:53: no such host"}
  unable to create topics [test]: unable to dial: dial tcp: lookup cluster-tls-0.cluster-tls.operator-1azamhsqno.svc.cluster.local on 10.96.0.10:53: no such host
```

https://github.com/redpanda-data/helm-charts/actions/runs/6130129339/job/16638935698#step:12:16056

Unrelated error to the change.

Proposed fix in https://github.com/redpanda-data/helm-charts/pull/709

**Pull request merged**
