### PR TITLE
CODEOWNERS: Add chrisseto

### PR DESCRIPTION
**Pull request by chrisseto**
This commit adds me (chrisseto) to the list of codeowner for this repository and removes joejulian, who is no longer with red panda.

### CODE REVIEW

**Review by alejandroEsc — APPROVED** [review]
lgtm!

**Comment by andrewhsu** [comment]
i pushed commit f5ea5ba to trigger `lint` gha checks so the branch protection rule could be satisfied

**Review by andrewhsu — APPROVED** [review]
LGTM

**Comment by ivotron** [comment]
The files changed are tooling and not actual code we release, so it's OK to ignore the linter failure as it's not affected by this PR

**Pull request merged**
