### PR TITLE
commonLabels to console helm chart

### PR DESCRIPTION
**Pull request by bhataprameya**
Add commonLabels to the console helm chart.

This added custom Lable to all the components of the deployment

### CODE REVIEW

**Comment by bhataprameya** [comment]
> Hi @bhataprameya Can you approve CLA?

I already did. I am not sure why, its still shows not signed
Screenshot 2023-10-31 at 8 10 07 AM

**Review by alejandroEsc — APPROVED** [review]
lgtm

**Comment by joejulian** [comment]
@bhataprameya
```
Aprameya Bhat seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
```
The [email address](mailto:abhat@fanatics.com) you used to sign your commit and the email address you used to sign the CLA need to be the same and that address needs to be in your [github profile](https://github.com/settings/emails).

**Comment by bhataprameya** [comment]
> @bhataprameya
> 
> ```
> Aprameya Bhat seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> ```
> 
> The [email address](mailto:abhat@fanatics.com) you used to sign your commit and the email address you used to sign the CLA need to be the same and that address needs to be in your [github profile](https://github.com/settings/emails).

done. Its fixed now

**Pull request merged**
