### PR TITLE
Update to Redpanda v22.3.3

### PR DESCRIPTION
**Pull request by vuldin**
This makes `v22.3.3` the default Redpanda version. A previous PR added support for this version. I thought it would be appropriate to update the major version of the helm chart with this change, but let me know what you think.

### CODE REVIEW

**Comment by vuldin** [comment]
I'm able to run linting and tests locally without fail, but in the github tasks I get the following error:
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  91s                default-scheduler  0/5 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 4 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling.
```

**Comment by vuldin** [comment]
Not sure the warning I posted above is the actual issue... still looking into why it fails tests.

**Comment by joejulian** [comment]
Seems to be failing to connect to the schema registry https://github.com/redpanda-data/helm-charts/actions/runs/3474592907/jobs/5808030632#step:8:2567

```
*   Trying 10.244.3.3:8081...
* Connected to redpanda-5oy9oigaf1.redpanda-5oy9oigaf1.svc.cluster.local (10.244.3.3) port 8081 (#0)
> GET /subjects HTTP/1.1
> Host: redpanda-5oy9oigaf1.redpanda-5oy9oigaf1.svc.cluster.local:8081
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Operation timed out after 3000 milliseconds with 0 bytes received
* Closing connection 0
```

**Comment by joejulian** [comment]
unrelated, I think, but this needs fixed too:
https://github.com/redpanda-data/helm-charts/actions/runs/3474592907/jobs/5808030632#step:8:2374

**Comment by joejulian** [comment]
https://github.com/redpanda-data/helm-charts/blob/3d91a96b8c9dabb89dac498d38a308daaeb0425b/charts/redpanda/Chart.yaml#L45 needs to match the appVersion

**Review by joejulian — APPROVED** [review]

**Comment by vuldin** [comment]
Thanks @joejulian for figuring out the issue with falling tests, and updating to the latest redpanda v22.3.3.

**Pull request merged**
