### PR TITLE
bump version and bump annotation to proper version

### PR DESCRIPTION
**Pull request by alejandroEsc**

### CODE REVIEW

**Comment by RafalKorepta** [comment]
I wonder why our automation is not working as expected.

Today's nightly has 
```
nothing to update
```
https://github.com/redpanda-data/helm-charts/actions/runs/6192749166/job/16813277955#step:7:3

**Comment by RafalKorepta** [comment]
Last time it was autogenerated PR https://github.com/redpanda-data/helm-charts/pull/699 that didn't bump artifacthub.io/images

I will open PR to fix this.

**Comment by RafalKorepta** [comment]
I tried to fix all issues in https://github.com/redpanda-data/helm-charts/pull/726

**Review by joejulian — APPROVED** [review]

**Comment by alejandroEsc** [comment]
closing this.

**Pull request closed without merging**
