### PR TITLE
redpanda: Migrating a subset of _helpers.tpl to golang

### PR DESCRIPTION
**Pull request by chrisseto**
Show casing what using gotohelm looks like and experimenting with some
dev / CI configurations.

### CODE REVIEW

**Comment by chrisseto** [comment]
The existence of `git checkout main && git checkout -` in our workflows are causing some fun problems with `nix develop`.  I'm not sure why those are present and further more it's vexing that they're still being run despite me having removed them within this PR.

**Comment by chrisseto** [comment]
@alejandroEsc @RafalKorepta when you have a spare second, could you pull this branch and run `nix develop` and then `task charts:generate:redpanda && go test ./charts/redpanda` in the resultant subshell? Just want to double check that everything will work as expected on developer machines!

There will be some failures from `go test` as there's a bit of merge skew right now.

**Comment by chrisseto** [comment]
Huh... This looks like the errors I was hitting before making `genpartial`. I'll try to repro locally. Thanks!

**Comment by chrisseto** [comment]
No dice locally... I wonder if we'll want to switch to using `helm build` to get a built version of the chart within our tests. Just to reduce the overall moving parts?

**Review by RafalKorepta — APPROVED** [review]

**Pull request merged**
