### PR TITLE
Remove status field from resources

### PR DESCRIPTION
**Pull request by wdonne**
A Helm chart is not supposed to generate status fields in the resources. Although it may not change the behaviour in this case, it will keep the resource "out of sync" in GitOps tools.

### CODE REVIEW

**Comment by chrisseto** [comment]
Hey @wdonne! This approach is not going to work. Our charts are generated from a go code base. The generation (run in CI) will immediately overwrite your changes.

Our charts follow the JSON/YAML marshaling semantic of Go and therefore Kubernetes' types itself. The Status field is always included due to it go's zero value system but the Kubernetes API ignores any changes to it as it's a sub-resource. Can you provide a bit more information about what GitOps tool you're using the misbehavior you're experiencing?

**Comment by wdonne** [comment]
Hi @chrisseto ,

I understand that my changes won't work.

The GitOps tool I use is ArgoCD. It supports Helm charts. Since a rendered Helm chart is one big YAML file with all resources in it, it will be considered as the desired state. If the desired state contains non-empty status fields, then those resources will be out of sync immediately because the status is not supposed to be managed by ArgoCD but by the controller that owns the resource.

**Comment by chrisseto** [comment]
Interesting! I'd almost argue that's a bug in ArgoCD but we're really the exception here. I'll see what we can do.

**Comment by wdonne** [comment]
You could indeed say it is also a bug in ArgoCD because it never makes sense to compare the status fields.

**Comment by chrisseto** [comment]
See https://github.com/redpanda-data/helm-charts/pull/1462

**Pull request closed without merging**
